version: '3.8'

services:
  greatness_portfolio:
    build: .
    restart: always
    env_file:
      - .env
    depends_on:
      - mysql

  nginx:
    image: jonasal/nginx-certbot:latest
    restart: always
    environment:
      - CERTBOT_EMAIL=your-email@example.com
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./user_conf.d:/etc/nginx/user_conf.d
    depends_on:
      - greatness_portfolio

  mysql:
    image: mariadb:10.5
    restart: always
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mydatabase:/var/lib/mysql

volumes:
  mydatabase:
  nginx_secrets: 